# - job_name: "prometheus"
#   static_configs:
#   - targets: ["prometheus-operated.monitoring:9090"]
# - job_name: "alert"
#   static_configs:
#   - targets: ["alertmanager-operated.monitoring:9093"]