kind: Service
apiVersion: v1
metadata:
  namespace: myproject
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: web
    port: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: myproject
  name: grafana
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: grafana
  endpoints:
  - port: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: myproject
  name: grafana-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: grafana.minishift.local
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: web
