apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: myproject
  app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000140100
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - name: web
          containerPort: 3000
        resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: myproject
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: web
    port: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: myproject
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: grafana
  endpoints:
  - port: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: myproject
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: grafana.minishift.local
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: web