apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-exporter
  namespace: myproject
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: grafana
  endpoints:
  - name: web
    port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-service
  namespace: myproject
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: grafana.minishift.local
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana-exporter
          servicePort: web
