---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: grafana
  serviceMonitorNamespaceSelector:
    matchNames:
    - flux
    - myproject
    - monitoring
    - concourse
    - grafana
  namespaceSelector:
    matchNames:
    - flux
    - myproject
    - monitoring
    - concourse
    - grafana
  endpoints:
  - port: web