apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "job.name" . }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      initContainers:
      {{range .Values.dependencies}}
      - name: init-{{.}}
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup {{.}}; do echo waiting for {{.}}; sleep 2; done;']
      {{- end }}
      restartPolicy: Never
  backoffLimit: 4