apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  app: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000140100
      containers:
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - name: web
          containerPort: 9100
        resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
  - name: web
    port: 9100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-exporter
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: node-exporter.minishift.local
    http:
      paths:
      - path: /
        backend:
          serviceName: node-exporter
          servicePort: web