apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-operator
rules:
  - apiGroups:
      - integreatly.org
    resources:
      - services
      - serviceaccounts
      - grafanas
      - grafanas/finalizers
      - grafanadatasources
      - grafanadashboards
      - grafanadashboards/finalizers
    verbs: ['get', 'list', 'update', 'watch']
  - apiGroups:
    - ""
    resources:
    - serviceaccounts
    - services
    - services/finalizers
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    verbs:
    - '*'
  - apiGroups:
    - extensions
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
    - get
