apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  selector:
    matchLabels:
      app: concourse
  template:
    spec:
      securityContext:
        priviledged: false
        runAsUser: 1000140100
    metadata:
      namespace: concourse
      labels:
        app: concourse
  releaseName: concourse
  chart:
    name: concourse
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 8.2.2
  values:
    web:  
      enabled: true
      ingress:
        enabled: true
        # annotations:
        #   - nginx.ingress.kubernetes.io/rewrite-target: /
        hosts: 
            - concourse.minishift.local
    concourse:
      web:  
        prometheus:
          enabled: true
        externalUrl: concourse.minishift.local
    worker:
      spec:
        initContainers:
          securityContext:
            privileged: false
            runAsUser: 1000140550
      securityContext:
        enabled: false
      serviceAccount:
        enabled: true
    # metrics:
    #   enabled: true
    postgresql:
      persistence:
        enabled: false
      serviceAccount:
        enabled: true
      spec:
        initContainers:
          securityContext:
            runAsUser: 1000140100 
      securityContext:
        enabled: false
        # fsGroup: 5555
        # runAsUser: 1000140100
        # runAsNonRoot: true
        securityContext:
          enabled: false
          fsGroup: 5055
          runAsUser: 1000140100
          runAsNonRoot: true
      metrics:
        enabled: true  
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: concourse
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: concourse-web
  serviceMonitorNamespaceSelector:
    matchNames:
    - flux
    - myproject
    - monitoring
    - concourse
  namespaceSelector:
    matchNames:
    - flux
    - myproject
    - monitoring
    - concourse
  endpoints:
  - port: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: concourse-postgres
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: concourse-web
  serviceMonitorNamespaceSelector:
    matchNames:
    - flux
    - myproject
    - monitoring
    - concourse
  namespaceSelector:
    matchNames:
    - flux
    - myproject
    - monitoring
    - concourse
  endpoints:
  - port: prometheus