apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse
  namespace: myproject
spec:
  replicas: 3
  selector:
    matchLabels:
      name: concourse
  template:
    metadata:
      labels:
        name: concourse
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000140100
      containers:
      - name: concourse
        image: concourse/concourse
        ports:
        - name: web
          containerPort: 9391
        - name: ui
          containerPort: 8080
        resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: concourse
  namespace: myproject
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      name: concourse
  endpoints:
  - port: web