apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: myproject
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  selector:
    matchLabels:
      app: concourse
  template:
    spec:
      securityContext:
        priviledged: true
    metadata:
      namespace: myproject
      labels:
        app: concourse
  releaseName: concourse
  chart:
    name: concourse
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 8.2.2
  values:
    prometheus:
      enabled: true
    spec:
      initContainers:
        securityContext:
          privileged: false
    metrics:
      enabled: true
    postgresql:
      serviceAccount:
        enabled: true
      spec:
        initContainers:
          securityContext:
            runAsUser: 1000140100 
      securityContext:
        enabled: false
        fsGroup: 5555
        runAsUser: 1000140100
        runAsNonRoot: true
        securityContext:
          enabled: false
          fsGroup: 5055
          runAsUser: 1000140100
          runAsNonRoot: true
      metrics:
        enabled: true  
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: concourse
  namespace: myproject
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: concourse-web
  endpoints:
  - port: prometheus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: concourse-web
  namespace: myproject
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: concourse.minishift.local
    http:
      paths:
      - path: /
        backend:
          serviceName: concourse-web
          servicePort: atc