apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: myproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000140100
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
        resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: example-deployment
spec:
  type: NodePort
  ports:
  - name: web
    # nodePort: 8080
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: example-deployment
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-deployment
  app: example-deployment
  namespace: myproject
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-deployment
  endpoints:
  - port: web 