apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux
  namespace: myproject
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: flux
  serviceMonitorNamespaceSelector:
    matchNames:
    - flux
    - myproject
  namespaceSelector:
    matchNames:
    - flux
    - myproject
  endpoints:
  - port: http