apiVersion: v1
data:
  helm-repositories.yaml: YXBpVmVyc2lvbjogdjEKcmVwb3NpdG9yaWVzOgotIGNhRmlsZTogIiIKICBjYWNoZTogL3Zhci9mbHV4ZC9oZWxtL3JlcG9zaXRvcnkvY2FjaGUvc3RhYmxlLWluZGV4LnlhbWwKICBjZXJ0RmlsZTogIiIKICBrZXlGaWxlOiAiIgogIG5hbWU6IHN0YWJsZQogIHBhc3N3b3JkOiAiIgogIHVybDogaHR0cHM6Ly9rdWJlcm5ldGVzLWNoYXJ0cy5zdG9yYWdlLmdvb2dsZWFwaXMuY29tCiAgdXNlcm5hbWU6ICIi
kind: Secret
metadata:
  creationTimestamp: null
  name: flux-helm-repositories
  namespace: flux
