kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-operator
subjects:
- kind: ServiceAccount
  name: grafana-operator
  namespace: myproject
roleRef:
  kind: Role
  name: grafana-operator
  apiGroup: rbac.authorization.k8s.io