{
 "title": "Concourse",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "deployment", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Concourse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduling: Full",
   "type": "graph",
   "description": "Show the time taken to schedule a build each pipeline.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "pipeline" ], "type": "tag" }
     ],
     "groupByTags": [ "pipeline" ],
     "measurement": "scheduling: full duration (ms)",
     "query": "SELECT mean(value) FROM \"scheduling: full duration (ms)\" WHERE $timeFilter GROUP BY time($dynamic), \"pipeline\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Build Statuses",
   "type": "graph",
   "description": "Shows the number of finished build over time with their statuses (succeeded, failed, aborted & errored).",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "succeeded",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "succeeded" }
     ]
    },
    {
     "alias": "errored",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "errored" }
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "failed" }
     ]
    },
    {
     "alias": "aborted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "aborted" }
     ]
    }
   ]
  },
  {
   "title": "Builds Started/Finished",
   "type": "graph",
   "description": "Shows the number of builds started and finished over time.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build started",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Checks",
   "type": "graph",
   "description": "Shows the number of resource checks done per team.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "resource checked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Web",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Memory",
     "type": "graph",
     "description": "Shows the percentage of memory used (without counting cache) by the web instance.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "groupByTags": [ "host" ],
       "measurement": "mem",
       "query": "SELECT mean(value) * 100 FROM \"memory\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "=", "value": "web" },
        { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "groupByTags": [ "host" ],
       "measurement": "mem",
       "query": "SELECT mean(value) * 100 FROM \"memory\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "=", "value": "concourse" },
        { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
       ]
      }
     ]
    },
    {
     "title": "Web Open Files",
     "type": "graph",
     "description": "Shows the number of open files that belong to ATC.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "groupByTags": [ "host" ],
       "measurement": "procstat",
       "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
       "select": [
        [
         { "params": [ "num_fds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "=", "value": "web" },
        { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/^concourse-$deployment$/" }
       ]
      }
     ]
    },
    {
     "title": "Web CPU",
     "type": "graph",
     "description": "Shows the percentage of CPU usage in user space by each web instance.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "groupByTags": [ "host" ],
       "measurement": "cpu",
       "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "=", "value": "web" },
        { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "groupByTags": [ "host" ],
       "measurement": "cpu",
       "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "=", "value": "concourse" },
        { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
       ]
      }
     ]
    },
    {
     "title": "Web Network",
     "type": "graph",
     "description": "Shows the transmission/receive rate of the web eth0 network interface.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "received {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bosh-job" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
        { "condition": "AND", "key": "bosh-job", "operator": "=", "value": "web" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      },
      {
       "alias": "sent {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "bosh-job" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
        { "condition": "AND", "key": "bosh-job", "operator": "=", "value": "web" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Web Goroutines",
     "type": "graph",
     "description": "Shows the number of the current running go routines for the web instances.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "groupByTags": [ "host" ],
       "measurement": "goroutines",
       "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "=", "value": "web" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "groupByTags": [ "host" ],
       "measurement": "goroutines",
       "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "=", "value": "concourse" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "goroutines",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-job", "operator": "!~", "value": "/.*(web|concourse).*/" }
       ]
      }
     ]
    },
    {
     "title": "HTTP Response Duration",
     "type": "graph",
     "description": "Shows the response time of every call per possible route.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "fields": [
        { "func": "max", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "route" ], "type": "tag" }
       ],
       "groupByTags": [ "route" ],
       "measurement": "http response time",
       "query": "SELECT mean(\"value\") FROM \"http response time\" WHERE $timeFilter GROUP BY time($interval), \"route\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Web Database Connections",
     "type": "graph",
     "description": "The number of open database connections per ATC node for both api and backend connection pools.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "ConnectionName" ], "type": "tag" }
       ],
       "measurement": "database connections",
       "query": "SELECT mean(\"value\") FROM \"scheduling: loading versions duration (ms)\" WHERE $timeFilter GROUP BY time($interval), \"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Database Queries (1m)",
     "type": "graph",
     "description": "The number of queries that got created since the last time the metric was emitted.\n\nNote: the emission interval is hardcoded to 10s.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "database queries",
       "query": "SELECT non_negative_derivative(max(\"value\"), 10s) FROM \"database queries\" WHERE $timeFilter GROUP BY time($interval), \"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Worker Load",
   "type": "graph",
   "description": "Shows the per-worker 1m load-average as reported by the worker's [telegraf][1] agent.\n\nThe number is a representation of running thread (task) demand on the system as an average number of running plus waiting threads (see [Linux Loading Averages][2]).\n\n*Note.: the numbers presented here are not relative to the number of CPUs.*\n\n[1]: https://github.com/influxdata/telegraf\n[2]: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"value\") * 100 FROM \"disk /var/vcap/data/baggageclaim/volumes\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"tag\", \"host\"",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "worker" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Disk Usage",
   "type": "graph",
   "description": "Displays the disk utilization of `/var/vcap/data` for bosh jobs `worker`, `concourse`, and `untrusted-worker`.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"value\") * 100 FROM \"disk /var/vcap/data/baggageclaim/volumes\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"tag\", \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/var/vcap/data" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"value\") * 100 FROM \"disk /var/vcap/data/baggageclaim/volumes\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"tag\", \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "concourse" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/var/vcap/data" }
     ]
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "graph",
   "description": "Shows the percentage of CPU usage in user space by each worker instance.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "concourse" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Network",
   "type": "graph",
   "description": "Shows the transmission/receive rate of the workers eth0 network interface.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Bytes received {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Bytes received {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Bytes sent {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=", "value": "concourse" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Bytes sent {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=", "value": "concourse" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Worker Containers",
   "type": "graph",
   "description": "Shows the number of active containers per worker as reported by the garden server on the worker.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_worker",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" }
     ],
     "measurement": "worker containers",
     "query": "SELECT mean(\"value\") FROM \"worker containers\" WHERE \"bosh-deployment\" = 'concourse-wings' AND $timeFilter GROUP BY time($__interval), \"worker\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Memory",
   "type": "graph",
   "description": "Shows the percentage of memory used (without counting cache) by the worker instances (per worker).",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "measurement": "mem",
     "query": "SELECT mean(value) * 100 FROM \"memory\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "measurement": "mem",
     "query": "SELECT mean(value) * 100 FROM \"memory\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "concourse" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Worker Volumes",
   "type": "graph",
   "description": "Shows the number of active volumes per worker as reported by the baggageclaim server on the worker.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" }
     ],
     "measurement": "worker volumes",
     "query": "SELECT mean(\"value\") FROM \"cpu\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "exe" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_fds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "worker" }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes",
     "type": "graph",
     "description": "Shows: \n - `worker volumes.sum`: The number of volumes reported by the worker on registration and on heartbeating.\n - `volumes created.sum`: The number of created volumes since the last metric emit as \n - `failed volumes.sum`: The number of volumes that failed to be created since the last metric emit.\n - `volumes deleted.sum`: The number of deleted volumes after the last metric emit",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "volumes created",
       "query": "SELECT sum(\"value\") FROM \"containers created\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "volumes deleted",
       "query": "SELECT sum(\"value\") FROM \"containers deleted\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker volumes",
       "query": "SELECT sum(\"value\") FROM \"containers deleted\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "failed volumes",
       "query": "SELECT sum(\"value\") FROM \"containers deleted\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Volumes Created",
     "type": "graph",
     "description": "The number of volumes that were successfully created by baggageclaim since the last time the metric was emitted.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "volumes created",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Volumes Found For Deletion",
     "type": "graph",
     "description": "Generally shows the volumes that are about to be cleaned up.\n - `created`: volumes that are in the `created` state but not assigned to any container, resource cache or task.\n - `Orphaned`: volumes which are in the `destroying` state in the db.\n - `failed`: volumes that are in the `failed` state.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "created",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "created volumes to be garbage collected",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "failed volumes to be garbage collected",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "alias": "orphaned",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "orphaned volumes to be garbage collected",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Volumes Deleted",
     "type": "graph",
     "description": "The number of containers per atc node that were removed from the database since the last time the metric was emitted.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "volumes deleted",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Destroying Volumes Listed",
     "type": "graph",
     "description": "shows orphaned volumes which are in the destroying state in the db.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "orphaned volumes to be garbage collected",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Containers",
   "type": "graph",
   "description": "Shows: \n - `worker containers.sum`: The number of containers reported by the worker on registration and on heartbeating.\n - `containers created.sum`: The number of created containers since the last metric emit as \n - `failed containers.sum`: The number of containers that failed to be created since the last metric emit.\n - `containers deleted.sum`: The number of deleted containers after the last metric emit.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "containers created",
     "query": "SELECT sum(\"value\") FROM \"containers created\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "containers deleted",
     "query": "SELECT sum(\"value\") FROM \"containers deleted\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worker containers",
     "query": "SELECT sum(\"value\") FROM \"containers deleted\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "failed containers",
     "query": "SELECT sum(\"value\") FROM \"containers deleted\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Containers Created",
   "type": "graph",
   "description": "The number of containers that were successfully created in garden since the last time the metric was emitted.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "containers created",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Containers Found For Deletion",
   "type": "graph",
   "description": "- Generally shows the containers that are about to be cleaned up.\n - `Created`, `Creating`, `Destroying`: The number of containers that are considered `orphaned` and in the respective state. \n - Orphaned containers are the ones which:\n   - are not assigned to any builds, get or check steps, or have a config check session. \n   - are in `creating` state and assigned to any check or get steps.\n - `failed`: containers that are in failed state.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "created",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "created containers to be garbage collected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    },
    {
     "alias": "creating",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "creating containers to be garbage collected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    },
    {
     "alias": "destroying",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "destroying containers to be garbage collected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "failed containers to be garbage collected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Containers Deleted",
   "type": "graph",
   "description": "The number of containers that were removed from the database since the last time the metric was emitted per atc node.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "containers deleted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}